#!/usr/bin/env bash
# Fetch Cognito IDs from a deployed stack and write a local .env file.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV="${1:-dev}"
REGION="ap-southeast-1"

ACCOUNTS_JSON="${ROOT}/infra/environments/accounts.json"
STACK_NAME=$(node -e "const a=require('${ACCOUNTS_JSON}');console.log(a.accounts['${ENV}'].stackName)")
PROFILE=$(node -e "const a=require('${ACCOUNTS_JSON}');console.log(a.accounts['${ENV}'].profile)")

AWS_ARGS=(--region "$REGION" --profile "$PROFILE")

POOL_ID=$(aws cloudformation describe-stacks "${AWS_ARGS[@]}" \
  --stack-name "$STACK_NAME" \
  --query "Stacks[0].Outputs[?OutputKey=='CognitoUserPoolId'].OutputValue" \
  --output text)

CLIENT_ID=$(aws cloudformation describe-stacks "${AWS_ARGS[@]}" \
  --stack-name "$STACK_NAME" \
  --query "Stacks[0].Outputs[?OutputKey=='CognitoClientId'].OutputValue" \
  --output text)

AURORA=$(aws cloudformation describe-stacks "${AWS_ARGS[@]}" \
  --stack-name "$STACK_NAME" \
  --query "Stacks[0].Outputs[?OutputKey=='AuroraEndpoint'].OutputValue" \
  --output text)

ENV_FILE="${ROOT}/.env"
cat > "$ENV_FILE" <<EOF
# Generated by bootstrap-local-env.sh for ${ENV}
NEXT_PUBLIC_WEB_URL=http://localhost:3000
ARIA_PUBLIC_URL=http://localhost:3000

NEXT_PUBLIC_COGNITO_REGION=${REGION}
NEXT_PUBLIC_COGNITO_USER_POOL_ID=${POOL_ID}
NEXT_PUBLIC_COGNITO_CLIENT_ID=${CLIENT_ID}

# Fetch password from Secrets Manager: aria/${ENV}/db-master
# DATABASE_URL=postgresql://aria_app:PASSWORD@${AURORA}:5432/aria?sslmode=require
DATABASE_URL=

BEDROCK_API_KEY=
BEDROCK_REGION=${REGION}
BEDROCK_MODEL_ID=apac.amazon.nova-micro-v1:0
BEDROCK_ENABLE_SEARCH=false
EOF

echo "Wrote ${ENV_FILE}"
echo "Fill DATABASE_URL (from aria/${ENV}/db-master) and BEDROCK_API_KEY, then run: npm run dev"
